package app.taolin.one.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARTICLE".
*/
public class ArticleDao extends AbstractDao<Article, String> {

    public static final String TABLENAME = "ARTICLE";

    /**
     * Properties of entity Article.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Subtitle = new Property(2, String.class, "subtitle", false, "SUBTITLE");
        public final static Property Author = new Property(3, String.class, "author", false, "AUTHOR");
        public final static Property Authit = new Property(4, String.class, "authit", false, "AUTHIT");
        public final static Property Authorintro = new Property(5, String.class, "authorintro", false, "AUTHORINTRO");
        public final static Property Content = new Property(6, String.class, "content", false, "CONTENT");
        public final static Property Makettime = new Property(7, String.class, "makettime", false, "MAKETTIME");
        public final static Property Updatedate = new Property(8, String.class, "updatedate", false, "UPDATEDATE");
        public final static Property Weburl = new Property(9, String.class, "weburl", false, "WEBURL");
        public final static Property Guideword = new Property(10, String.class, "guideword", false, "GUIDEWORD");
        public final static Property Audio = new Property(11, String.class, "audio", false, "AUDIO");
        public final static Property Praisenum = new Property(12, int.class, "praisenum", false, "PRAISENUM");
        public final static Property Sharenum = new Property(13, int.class, "sharenum", false, "SHARENUM");
        public final static Property Commentnum = new Property(14, int.class, "commentnum", false, "COMMENTNUM");
        public final static Property Isloaded = new Property(15, boolean.class, "isloaded", false, "ISLOADED");
    };


    public ArticleDao(DaoConfig config) {
        super(config);
    }
    
    public ArticleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARTICLE\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"SUBTITLE\" TEXT NOT NULL ," + // 2: subtitle
                "\"AUTHOR\" TEXT NOT NULL ," + // 3: author
                "\"AUTHIT\" TEXT NOT NULL ," + // 4: authit
                "\"AUTHORINTRO\" TEXT NOT NULL ," + // 5: authorintro
                "\"CONTENT\" TEXT NOT NULL ," + // 6: content
                "\"MAKETTIME\" TEXT NOT NULL ," + // 7: makettime
                "\"UPDATEDATE\" TEXT NOT NULL ," + // 8: updatedate
                "\"WEBURL\" TEXT NOT NULL ," + // 9: weburl
                "\"GUIDEWORD\" TEXT NOT NULL ," + // 10: guideword
                "\"AUDIO\" TEXT NOT NULL ," + // 11: audio
                "\"PRAISENUM\" INTEGER NOT NULL ," + // 12: praisenum
                "\"SHARENUM\" INTEGER NOT NULL ," + // 13: sharenum
                "\"COMMENTNUM\" INTEGER NOT NULL ," + // 14: commentnum
                "\"ISLOADED\" INTEGER NOT NULL );"); // 15: isloaded
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARTICLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Article entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getId());
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getSubtitle());
        stmt.bindString(4, entity.getAuthor());
        stmt.bindString(5, entity.getAuthit());
        stmt.bindString(6, entity.getAuthorintro());
        stmt.bindString(7, entity.getContent());
        stmt.bindString(8, entity.getMakettime());
        stmt.bindString(9, entity.getUpdatedate());
        stmt.bindString(10, entity.getWeburl());
        stmt.bindString(11, entity.getGuideword());
        stmt.bindString(12, entity.getAudio());
        stmt.bindLong(13, entity.getPraisenum());
        stmt.bindLong(14, entity.getSharenum());
        stmt.bindLong(15, entity.getCommentnum());
        stmt.bindLong(16, entity.getIsloaded() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Article entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getId());
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getSubtitle());
        stmt.bindString(4, entity.getAuthor());
        stmt.bindString(5, entity.getAuthit());
        stmt.bindString(6, entity.getAuthorintro());
        stmt.bindString(7, entity.getContent());
        stmt.bindString(8, entity.getMakettime());
        stmt.bindString(9, entity.getUpdatedate());
        stmt.bindString(10, entity.getWeburl());
        stmt.bindString(11, entity.getGuideword());
        stmt.bindString(12, entity.getAudio());
        stmt.bindLong(13, entity.getPraisenum());
        stmt.bindLong(14, entity.getSharenum());
        stmt.bindLong(15, entity.getCommentnum());
        stmt.bindLong(16, entity.getIsloaded() ? 1L: 0L);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public Article readEntity(Cursor cursor, int offset) {
        Article entity = new Article( //
            cursor.getString(offset + 0), // id
            cursor.getString(offset + 1), // title
            cursor.getString(offset + 2), // subtitle
            cursor.getString(offset + 3), // author
            cursor.getString(offset + 4), // authit
            cursor.getString(offset + 5), // authorintro
            cursor.getString(offset + 6), // content
            cursor.getString(offset + 7), // makettime
            cursor.getString(offset + 8), // updatedate
            cursor.getString(offset + 9), // weburl
            cursor.getString(offset + 10), // guideword
            cursor.getString(offset + 11), // audio
            cursor.getInt(offset + 12), // praisenum
            cursor.getInt(offset + 13), // sharenum
            cursor.getInt(offset + 14), // commentnum
            cursor.getShort(offset + 15) != 0 // isloaded
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Article entity, int offset) {
        entity.setId(cursor.getString(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setSubtitle(cursor.getString(offset + 2));
        entity.setAuthor(cursor.getString(offset + 3));
        entity.setAuthit(cursor.getString(offset + 4));
        entity.setAuthorintro(cursor.getString(offset + 5));
        entity.setContent(cursor.getString(offset + 6));
        entity.setMakettime(cursor.getString(offset + 7));
        entity.setUpdatedate(cursor.getString(offset + 8));
        entity.setWeburl(cursor.getString(offset + 9));
        entity.setGuideword(cursor.getString(offset + 10));
        entity.setAudio(cursor.getString(offset + 11));
        entity.setPraisenum(cursor.getInt(offset + 12));
        entity.setSharenum(cursor.getInt(offset + 13));
        entity.setCommentnum(cursor.getInt(offset + 14));
        entity.setIsloaded(cursor.getShort(offset + 15) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(Article entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Article entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
