package app.taolin.one.dao;

import org.greenrobot.greendao.annotation.*;

import app.taolin.one.models.BaseArticle;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ARTICLE".
 */
@Entity
public class Article implements BaseArticle {

    @Id
    @NotNull
    private String id;

    @NotNull
    private String title;
    private String subTitle;
    private String author;
    private String authorDesc;
    private String weibo;
    private String authorIntro;
    private String content;
    private String webLink;

    @NotNull
    private String makeTime;

    @NotNull
    private String guideWord;
    private boolean isloaded;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Article() {
    }

    public Article(String id) {
        this.id = id;
    }

    @Generated
    public Article(String id, String title, String subTitle, String author, String authorDesc, String weibo, String authorIntro, String content, String webLink, String makeTime, String guideWord, boolean isloaded) {
        this.id = id;
        this.title = title;
        this.subTitle = subTitle;
        this.author = author;
        this.authorDesc = authorDesc;
        this.weibo = weibo;
        this.authorIntro = authorIntro;
        this.content = content;
        this.webLink = webLink;
        this.makeTime = makeTime;
        this.guideWord = guideWord;
        this.isloaded = isloaded;
    }

    @NotNull
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(@NotNull String id) {
        this.id = id;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    public String getSubTitle() {
        return subTitle;
    }

    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getAuthorDesc() {
        return authorDesc;
    }

    public void setAuthorDesc(String authorDesc) {
        this.authorDesc = authorDesc;
    }

    public String getWeibo() {
        return weibo;
    }

    public void setWeibo(String weibo) {
        this.weibo = weibo;
    }

    public String getAuthorIntro() {
        return authorIntro;
    }

    public void setAuthorIntro(String authorIntro) {
        this.authorIntro = authorIntro;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getWebLink() {
        return webLink;
    }

    public void setWebLink(String webLink) {
        this.webLink = webLink;
    }

    @NotNull
    public String getMakeTime() {
        return makeTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMakeTime(@NotNull String makeTime) {
        this.makeTime = makeTime;
    }

    @NotNull
    public String getGuideWord() {
        return guideWord;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGuideWord(@NotNull String guideWord) {
        this.guideWord = guideWord;
    }

    public boolean getIsloaded() {
        return isloaded;
    }

    public void setIsloaded(boolean isloaded) {
        this.isloaded = isloaded;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
