package app.taolin.one.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import app.taolin.one.dao.Home;
import app.taolin.one.dao.Question;
import app.taolin.one.dao.Article;

import app.taolin.one.dao.HomeDao;
import app.taolin.one.dao.QuestionDao;
import app.taolin.one.dao.ArticleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeDaoConfig;
    private final DaoConfig questionDaoConfig;
    private final DaoConfig articleDaoConfig;

    private final HomeDao homeDao;
    private final QuestionDao questionDao;
    private final ArticleDao articleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeDaoConfig = daoConfigMap.get(HomeDao.class).clone();
        homeDaoConfig.initIdentityScope(type);

        questionDaoConfig = daoConfigMap.get(QuestionDao.class).clone();
        questionDaoConfig.initIdentityScope(type);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        homeDao = new HomeDao(homeDaoConfig, this);
        questionDao = new QuestionDao(questionDaoConfig, this);
        articleDao = new ArticleDao(articleDaoConfig, this);

        registerDao(Home.class, homeDao);
        registerDao(Question.class, questionDao);
        registerDao(Article.class, articleDao);
    }
    
    public void clear() {
        homeDaoConfig.getIdentityScope().clear();
        questionDaoConfig.getIdentityScope().clear();
        articleDaoConfig.getIdentityScope().clear();
    }

    public HomeDao getHomeDao() {
        return homeDao;
    }

    public QuestionDao getQuestionDao() {
        return questionDao;
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

}
