package app.taolin.one.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOME".
*/
public class HomeDao extends AbstractDao<Home, String> {

    public static final String TABLENAME = "HOME";

    /**
     * Properties of entity Home.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Imgurl = new Property(2, String.class, "imgurl", false, "IMGURL");
        public final static Property Author = new Property(3, String.class, "author", false, "AUTHOR");
        public final static Property Content = new Property(4, String.class, "content", false, "CONTENT");
        public final static Property Makettime = new Property(5, String.class, "makettime", false, "MAKETTIME");
        public final static Property Updatedate = new Property(6, String.class, "updatedate", false, "UPDATEDATE");
        public final static Property Weburl = new Property(7, String.class, "weburl", false, "WEBURL");
        public final static Property Praisenum = new Property(8, int.class, "praisenum", false, "PRAISENUM");
        public final static Property Sharenum = new Property(9, int.class, "sharenum", false, "SHARENUM");
        public final static Property Commentnum = new Property(10, int.class, "commentnum", false, "COMMENTNUM");
        public final static Property Isloaded = new Property(11, boolean.class, "isloaded", false, "ISLOADED");
    };


    public HomeDao(DaoConfig config) {
        super(config);
    }
    
    public HomeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOME\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"IMGURL\" TEXT NOT NULL ," + // 2: imgurl
                "\"AUTHOR\" TEXT NOT NULL ," + // 3: author
                "\"CONTENT\" TEXT NOT NULL ," + // 4: content
                "\"MAKETTIME\" TEXT NOT NULL ," + // 5: makettime
                "\"UPDATEDATE\" TEXT NOT NULL ," + // 6: updatedate
                "\"WEBURL\" TEXT NOT NULL ," + // 7: weburl
                "\"PRAISENUM\" INTEGER NOT NULL ," + // 8: praisenum
                "\"SHARENUM\" INTEGER NOT NULL ," + // 9: sharenum
                "\"COMMENTNUM\" INTEGER NOT NULL ," + // 10: commentnum
                "\"ISLOADED\" INTEGER NOT NULL );"); // 11: isloaded
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOME\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Home entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getId());
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getImgurl());
        stmt.bindString(4, entity.getAuthor());
        stmt.bindString(5, entity.getContent());
        stmt.bindString(6, entity.getMakettime());
        stmt.bindString(7, entity.getUpdatedate());
        stmt.bindString(8, entity.getWeburl());
        stmt.bindLong(9, entity.getPraisenum());
        stmt.bindLong(10, entity.getSharenum());
        stmt.bindLong(11, entity.getCommentnum());
        stmt.bindLong(12, entity.getIsloaded() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Home entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getId());
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getImgurl());
        stmt.bindString(4, entity.getAuthor());
        stmt.bindString(5, entity.getContent());
        stmt.bindString(6, entity.getMakettime());
        stmt.bindString(7, entity.getUpdatedate());
        stmt.bindString(8, entity.getWeburl());
        stmt.bindLong(9, entity.getPraisenum());
        stmt.bindLong(10, entity.getSharenum());
        stmt.bindLong(11, entity.getCommentnum());
        stmt.bindLong(12, entity.getIsloaded() ? 1L: 0L);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public Home readEntity(Cursor cursor, int offset) {
        Home entity = new Home( //
            cursor.getString(offset + 0), // id
            cursor.getString(offset + 1), // title
            cursor.getString(offset + 2), // imgurl
            cursor.getString(offset + 3), // author
            cursor.getString(offset + 4), // content
            cursor.getString(offset + 5), // makettime
            cursor.getString(offset + 6), // updatedate
            cursor.getString(offset + 7), // weburl
            cursor.getInt(offset + 8), // praisenum
            cursor.getInt(offset + 9), // sharenum
            cursor.getInt(offset + 10), // commentnum
            cursor.getShort(offset + 11) != 0 // isloaded
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Home entity, int offset) {
        entity.setId(cursor.getString(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setImgurl(cursor.getString(offset + 2));
        entity.setAuthor(cursor.getString(offset + 3));
        entity.setContent(cursor.getString(offset + 4));
        entity.setMakettime(cursor.getString(offset + 5));
        entity.setUpdatedate(cursor.getString(offset + 6));
        entity.setWeburl(cursor.getString(offset + 7));
        entity.setPraisenum(cursor.getInt(offset + 8));
        entity.setSharenum(cursor.getInt(offset + 9));
        entity.setCommentnum(cursor.getInt(offset + 10));
        entity.setIsloaded(cursor.getShort(offset + 11) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(Home entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(Home entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
