package app.taolin.one.dao;

import org.greenrobot.greendao.annotation.*;

import app.taolin.one.models.BaseHome;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HOME".
 */
@Entity
public class Home implements BaseHome {

    @Id
    @NotNull
    private String id;

    @NotNull
    private String title;

    @NotNull
    private String imageUrl;

    @NotNull
    private String author;

    @NotNull
    private String content;

    @NotNull
    private String makeTime;

    @NotNull
    private String webLink;
    private boolean isloaded;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Home() {
    }

    public Home(String id) {
        this.id = id;
    }

    @Generated
    public Home(String id, String title, String imageUrl, String author, String content, String makeTime, String webLink, boolean isloaded) {
        this.id = id;
        this.title = title;
        this.imageUrl = imageUrl;
        this.author = author;
        this.content = content;
        this.makeTime = makeTime;
        this.webLink = webLink;
        this.isloaded = isloaded;
    }

    @NotNull
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(@NotNull String id) {
        this.id = id;
    }

    @NotNull
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(@NotNull String title) {
        this.title = title;
    }

    @NotNull
    public String getImageUrl() {
        return imageUrl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImageUrl(@NotNull String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @NotNull
    public String getAuthor() {
        return author;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAuthor(@NotNull String author) {
        this.author = author;
    }

    @NotNull
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(@NotNull String content) {
        this.content = content;
    }

    @NotNull
    public String getMakeTime() {
        return makeTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMakeTime(@NotNull String makeTime) {
        this.makeTime = makeTime;
    }

    @NotNull
    public String getWebLink() {
        return webLink;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWebLink(@NotNull String webLink) {
        this.webLink = webLink;
    }

    public boolean getIsloaded() {
        return isloaded;
    }

    public void setIsloaded(boolean isloaded) {
        this.isloaded = isloaded;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
