package app.taolin.one.dao;

import org.greenrobot.greendao.annotation.*;

import app.taolin.one.models.BaseQuestion;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "QUESTION".
 */
@Entity
public class Question implements BaseQuestion {

    @Id
    @NotNull
    private String id;

    @NotNull
    private String questionTitle;
    private String questionContent;

    @NotNull
    private String answerTitle;

    @NotNull
    private String answerContent;
    private String editor;
    private String webLink;

    @NotNull
    private String makeTime;
    private Boolean isloaded;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Question() {
    }

    public Question(String id) {
        this.id = id;
    }

    @Generated
    public Question(String id, String questionTitle, String questionContent, String answerTitle, String answerContent, String editor, String webLink, String makeTime, Boolean isloaded) {
        this.id = id;
        this.questionTitle = questionTitle;
        this.questionContent = questionContent;
        this.answerTitle = answerTitle;
        this.answerContent = answerContent;
        this.editor = editor;
        this.webLink = webLink;
        this.makeTime = makeTime;
        this.isloaded = isloaded;
    }

    @NotNull
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(@NotNull String id) {
        this.id = id;
    }

    @NotNull
    public String getQuestionTitle() {
        return questionTitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQuestionTitle(@NotNull String questionTitle) {
        this.questionTitle = questionTitle;
    }

    public String getQuestionContent() {
        return questionContent;
    }

    public void setQuestionContent(String questionContent) {
        this.questionContent = questionContent;
    }

    @NotNull
    public String getAnswerTitle() {
        return answerTitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAnswerTitle(@NotNull String answerTitle) {
        this.answerTitle = answerTitle;
    }

    @NotNull
    public String getAnswerContent() {
        return answerContent;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAnswerContent(@NotNull String answerContent) {
        this.answerContent = answerContent;
    }

    public String getEditor() {
        return editor;
    }

    public void setEditor(String editor) {
        this.editor = editor;
    }

    public String getWebLink() {
        return webLink;
    }

    public void setWebLink(String webLink) {
        this.webLink = webLink;
    }

    @NotNull
    public String getMakeTime() {
        return makeTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMakeTime(@NotNull String makeTime) {
        this.makeTime = makeTime;
    }

    public Boolean getIsloaded() {
        return isloaded;
    }

    public void setIsloaded(Boolean isloaded) {
        this.isloaded = isloaded;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
