package app.taolin.one.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "QUESTION".
 */
@Entity
public class Question {

    @Id
    @NotNull
    private String id;

    @NotNull
    private String questiontitle;

    @NotNull
    private String questioncontent;

    @NotNull
    private String answertitle;

    @NotNull
    private String answercontent;

    @NotNull
    private String makettime;

    @NotNull
    private String editor;

    @NotNull
    private String updatedate;

    @NotNull
    private String weburl;
    private int readnum;

    @NotNull
    private String guideword;
    private int praisenum;
    private int sharenum;
    private int commentnum;
    private boolean isloaded;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Question() {
    }

    public Question(String id) {
        this.id = id;
    }

    @Generated
    public Question(String id, String questiontitle, String questioncontent, String answertitle, String answercontent, String makettime, String editor, String updatedate, String weburl, int readnum, String guideword, int praisenum, int sharenum, int commentnum, boolean isloaded) {
        this.id = id;
        this.questiontitle = questiontitle;
        this.questioncontent = questioncontent;
        this.answertitle = answertitle;
        this.answercontent = answercontent;
        this.makettime = makettime;
        this.editor = editor;
        this.updatedate = updatedate;
        this.weburl = weburl;
        this.readnum = readnum;
        this.guideword = guideword;
        this.praisenum = praisenum;
        this.sharenum = sharenum;
        this.commentnum = commentnum;
        this.isloaded = isloaded;
    }

    @NotNull
    public String getId() {
        return id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setId(@NotNull String id) {
        this.id = id;
    }

    @NotNull
    public String getQuestiontitle() {
        return questiontitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQuestiontitle(@NotNull String questiontitle) {
        this.questiontitle = questiontitle;
    }

    @NotNull
    public String getQuestioncontent() {
        return questioncontent;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQuestioncontent(@NotNull String questioncontent) {
        this.questioncontent = questioncontent;
    }

    @NotNull
    public String getAnswertitle() {
        return answertitle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAnswertitle(@NotNull String answertitle) {
        this.answertitle = answertitle;
    }

    @NotNull
    public String getAnswercontent() {
        return answercontent;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAnswercontent(@NotNull String answercontent) {
        this.answercontent = answercontent;
    }

    @NotNull
    public String getMakettime() {
        return makettime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMakettime(@NotNull String makettime) {
        this.makettime = makettime;
    }

    @NotNull
    public String getEditor() {
        return editor;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEditor(@NotNull String editor) {
        this.editor = editor;
    }

    @NotNull
    public String getUpdatedate() {
        return updatedate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedate(@NotNull String updatedate) {
        this.updatedate = updatedate;
    }

    @NotNull
    public String getWeburl() {
        return weburl;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWeburl(@NotNull String weburl) {
        this.weburl = weburl;
    }

    public int getReadnum() {
        return readnum;
    }

    public void setReadnum(int readnum) {
        this.readnum = readnum;
    }

    @NotNull
    public String getGuideword() {
        return guideword;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGuideword(@NotNull String guideword) {
        this.guideword = guideword;
    }

    public int getPraisenum() {
        return praisenum;
    }

    public void setPraisenum(int praisenum) {
        this.praisenum = praisenum;
    }

    public int getSharenum() {
        return sharenum;
    }

    public void setSharenum(int sharenum) {
        this.sharenum = sharenum;
    }

    public int getCommentnum() {
        return commentnum;
    }

    public void setCommentnum(int commentnum) {
        this.commentnum = commentnum;
    }

    public boolean getIsloaded() {
        return isloaded;
    }

    public void setIsloaded(boolean isloaded) {
        this.isloaded = isloaded;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
